#!/usr/bin/env bash

set -e

DEFAULT_CONFIG_DIR="./common"
CONFIG_FILE="install.conf.yaml"
DOTBOT_DIR=".dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive

for dir in ${DEFAULT_CONFIG_DIR} ${@}; do
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}/${dir}" -c "${dir}/${CONFIG_FILE}" --plugin-dir "${BASEDIR}/.plugins"
done